platform :ios, '8.0'

use_frameworks!

def shared_pods
  pod 'Castle', :path => '../'
end

target 'Castle_Example' do
  shared_pods

  target 'Castle_Tests' do
    inherit! :search_paths    
  end
end

target 'Castle_UITests' do
  shared_pods
end
