platform :ios, '9.0'

use_frameworks!

def shared_pods
  pod 'Castle', :path => '../'
end

target 'Castle_Example' do
  shared_pods

  target 'Castle_Tests' do
    inherit! :search_paths    
  end
end

target 'Castle_UITests' do
  shared_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
	  target.build_configurations.each do |config|
	    config.build_settings['SWIFT_VERSION'] = '4.2'
	  end
  end
end