# Ordered by output of `jazzy --help config`

objc: true
umbrella_header: Castle/Classes/Castle.h
author: Castle
author_url: https://castle.io
module: Castle
github_url: https://github.com/castle/castle-ios
github_file_prefix: https://github.com/castle/castle-ios/tree/3.1.4
