# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- travis_retry set -o pipefail && xcodebuild test -workspace Example/Castle.xcworkspace -scheme Castle-Example -sdk iphonesimulator10.3 ONLY_ACTIVE_ARCH=NO VALID_ARCHS=x86_64 -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.0' GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty
- pod lib lint
after_success:
- bash <(curl -s https://codecov.io/bash)