# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Create XCFramework"
  lane :xcframework do
    clean_build_artifacts

    FileUtils.mkdir_p(File.expand_path("../Products/Castle.framework"))
    FileUtils.cp_r(File.expand_path("../Castle/Highwind.xcframework"), File.expand_path("../Products/Castle.framework/Highwind.xcframework"))
    FileUtils.cp_r(File.expand_path("../Castle/GeoZip.xcframework"), File.expand_path("../Products/Castle.framework/GeoZip.xcframework"))

    create_xcframework(
        workspace: 'Castle.xcworkspace',
        scheme: 'Castle',
        include_BCSymbolMaps: true,
        include_dSYMs: false,
        include_debug_symbols: true,
        include_bitcode: false,
        destinations: ['iOS'],
        xcframework_output_directory: 'Products/xcframeworks',
    )

    FileUtils.cp_r(File.expand_path("../Products/xcframeworks/Castle.xcframework"), File.expand_path("../Products/Castle.framework/Castle.xcframework"))

    zip(
        path: "Products/Castle.framework",
        output_path: "Products/Castle.framework.zip",
        exclude: "**/.DS_Store"
    )
  end
end
